# Generated by Django 3.1 on 2020-09-11 09:43

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=phone_field.models.PhoneField(blank=True, default=91, help_text='Contact phone number', max_length=31),
            preserve_default=False,
        ),
    ]
